minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - "@olinfo/*"

overrides:
  "better-call": "1.3.7"
  pdfjs-dist: "5.4.296"
  "@napi-rs/canvas": "^0.1.100"

allowBuilds:
  "@prisma/engines": false
  esbuild: false
  prisma: false
  protobufjs: false
  sharp: false
