FROM node:20 AS builder

ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

COPY ./ ./

LABEL org.opencontainers.image.source=https://github.com/olimpiadi-informatica/cmsocial

CMD ["yarn", "dev"]
EXPOSE 3000
