FROM node:20 AS builder

ENV NEXT_TELEMETRY_DISABLED=1

WORKDIR /app

RUN npm install -g pnpm@latest

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile

COPY ./ ./

LABEL org.opencontainers.image.source=https://github.com/olimpiadi-informatica/cmsocial

CMD ["pnpm", "dev"]
EXPOSE 3000
