name: Build

on:
  pull_request:
  push:
    branches-ignore: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Build
        run: pnpm build
