name: Check translations

on:
  push:
  pull_request:

jobs:
  translations:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        uses: pnpm/action-setup@v4
        with:
          version: latest
          run_install: true

      - name: Extract translations
        run: pnpm translate

      - name: Check for outdated translations
        run: git diff --exit-code
